config/routes.rb
Rails.application.routes.draw do
  resources :users
  root 'welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
	after_create_commit {broadcast_prepend_to "users"}
	after_update_commit {broadcast_replace_to "users"}
	validates :name, :address, presence: true
  validates :email, :contact, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all.reverse
    @user = User.new
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)


    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: "User was successfully created." }
        format.turbo_stream {render turbo_stream: turbo_stream.append('users', partial: 'users/user', locals: { user: @user })}
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace('user', partial: 'users/form', locals: { user: @user }) }
        format.html {render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:id, :name, :email, :address, :contact)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
  <!DOCTYPE html>
  <html>
    <head>
      <title>DemoAjax</title>
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag "application", "data-turbo-track": "reload", defer: true %>
      <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
      <%= turbo_include_tags %>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

    </head>

    <body>
      <script>
        $(document).ready(function () {
          $('[data-bs-toggle="dropdown"]').dropdown();
        });
      </script>
      <%= render "shared/header" %>
      <%= yield %>
      <%= turbo_frame_tag "user" %>
      <%= render "shared/footer" %>
    </body>
  </html>

app/views/shared/_footer.html.erb
<footer class="mt-5 bg-primary p-3">
	<div class="container">
		<div class="row">
			<div class="cl-lg-12">
				<h1 class="text-white">AJAX Demo App</h1>
			</div>
		</div>
	</div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">AJAX</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/users">Users</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/users/_form.html.erb
<%= turbo_frame_tag :users, target: :_top do %>
  
        <%= form_with model: user,id: dom_id(user), local: false , controller: "new-user" do |form| %>
          <div class="modal-body">
            <div class="form-group mt-3">
              <%= form.label :name,  style: "display: block", for: "name-id"  %>
              <%= form.text_field :name, class: "form-control",id: "name-id", autocomplete: "name" %>
            </div>
            <div class="form-group mt-3">
              <%= form.label :email, style: "display: block", for: "email-id"  %>
              <%= form.text_field :email, class: "form-control", id: "email-id", autocomplete: "email"  %>
            </div>
            <div class="form-group mt-3">
              <%= form.label :address, style: "display: block", for: "address-id" %>
              <%= form.text_field :address, class: "form-control", id: "address-id", autocomplete: "address" %>
            </div>
            <div class="form-group mt-3">
              <%= form.label :contact, style: "display: block", for: "contact-id" %>
              <%= form.text_field :contact, class: "form-control", id: "contact-id", autocomplete: "contact"  %>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary btn-lg" data-bs-dismiss="modal">Close</button>        
            <%= form.submit class: "btn btn-primary btn-lg", id: "submit-id", data: {action: 'users_controller#create'} %>
          </div>    
        <% end %>

<% end %>

  

app/views/users/_user.html.erb
<%= turbo_frame_tag dom_id(user) do %>
  <div id="<%= dom_id user %>">
    <p>
      <strong>Name:</strong>
      <%= user.name %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= user.email %>
    </p>

    <p>
      <strong>Address:</strong>
      <%= user.address %>
    </p>

    <p>
      <strong>Contact:</strong>
      <%= user.contact %>
    </p>

  </div>
<% end %>

app/views/users/create.turbo_stream.erb
<%= turbo_stream.replace 'user_form', partial: 'users/form', locals: { user: User.new } %>
<% if @user.errors.any? %>
  <%= turbo_stream.append 'flash-messages', partial: 'shared/flash', locals: { message: 'User creation failed. Please check your input.' } %>
  console.log("triggered")
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="cl-lg-5">
      <h1>Editing user</h1>

      <%= render "form", user: @user %>

      <br>

      <div>
        <%= link_to "Show this user", @user, class: "btn btn-primary btn-lg" %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<%= turbo_stream_from "users" %>

<div class="container">
  <div class="row">
    <div class="cl-lg-5 md-mx-auto">
      <h1>Users</h1>

      <%= link_to "New", new_user_path,class: "btn btn-primary btn-lg", data: { bs_toggle: "modal", bs_target: "#newUserModal", remote: true, controller: "new-user" } %>
      <br>
      <div id="users" class="mt-5">
        <% @users.each do |user| %>
          <div class="card card-body">
            <%= render user%>
            <div class="dropdown">
              <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown"  aria-expanded="false">
              CRUD
              </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <li><%= link_to "Show", user, class: "dropdown-item" %></li>
                <li><%= link_to "Edit", edit_user_path(user), class: "dropdown-item" %></li>
                <li> <%= button_to "Destroy", user, method: :delete, data: { confirm: 'Are you sure?' }, class: "dropdown-item " %></li>
              </ul>
            </div>
          </div>
          <br>
          <br>
        <% end %>
      </div>
      <%= link_to "New user", new_user_path , class: "btn btn-primary btn_lg" %>
    </div>
  </div>
</div>




<!-- Modal -->
<div class="modal fade" id="newUserModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-controller="modals">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Create New User</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <%= render 'form' , user: @user%>

      </div>
    </div>
  </div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="cl-lg-5">
      <h1>New user</h1>
      <turbo-frame id="newUserForm">
        <%= render 'form', user: @user %>
      </turbo-frame>
    </div>
  </div>
</div>

app/views/users/new.js.erb
$("#newUserForm").html(<%= escape_javascript render('form', user: @user) %>)
console.log("triggered");

app/views/users/new.turbo_stream.erb
<%= turbo_stream.replace 'user' do %>
	<%= render 'form' %>
<%= end %>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="cl-lg-5">
      <p style="color: green"><%= notice %></p>

      <%= render @user %>

      <div>
        <%= link_to "Edit this user", edit_user_path(@user), class: "btn btn-primary btn-lg" %> |
        <%= link_to "Back to users", users_path , class: "btn btn-outline-primary btn-lg" %> |

        <%= link_to "Destroy this user", @user, method: :delete, class: "btn btn-danger btn-lg"  %>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="container">
	<div class="row">
		<div class="col lg-9 mt-5">
			<div class="card shadow">
				<div class="card-body">
					<p class="lead fw-bold">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
					<%= link_to "Learn More", "javascript:void(0)", class: "btn btn-primary btn-dark" %>
				</div>
			</div>
		</div>
	</div>
</div>